#!/bin/sh

# Rodar o Detekt e salvar a saída
# OUTPUT=$(./gradlew detekt)

# Capturar o código de retorno do Detekt
# RESULT=$?

# Se o código de retorno for diferente de 0, significa que houve falha no Detekt
# if [ $RESULT -ne 0 ]; then
#   echo "Detekt encontrou erros nos seguintes arquivos:"
#   echo "$OUTPUT" | grep -iE "(error|warning|at:)"
#   echo "O push foi abortado. Por favor, corrija os erros e tente novamente."
#   exit 1
# fi

# Rodar o SpotlessCheck
./gradlew spotlessCheck
RESULT_SPOTLESS=$?

if [ $RESULT_SPOTLESS -ne 0 ]; then
  echo "****************************************************************"
  echo "                     Spotless formatting                        "
  echo " Spotless found formatting issues. Fixing them automatically... "
  echo "****************************************************************"

  # Rodar o SpotlessApply para corrigir automaticamente os erros
  ./gradlew spotlessApply
  RESULT_SPOTLESS_APPLY=$?

  if [ $RESULT_SPOTLESS_APPLY -ne 0 ]; then
    echo "***********************************************"
    echo "                 Spotless failed               "
    echo " Please fix the above issues before committing "
    echo "***********************************************"
    exit 1
  else
    echo "The formatting corrections have been applied successfully. Continuing..."
  fi
fi

# Executar Detekt
./gradlew test
RESULT_DETEKT=$?

if [ $RESULT_DETEKT -ne 0 ]; then
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit 1
fi

# Executar os testes unitários
#./gradlew test
#RESULT_UNIT_TEST=$?
#
#if [ $RESULT_UNIT_TEST -ne 0 ]; then
#  echo "*************************************************"
#  echo "                 Unit tests failed               "
#  echo " Please fix the above issues before committing   "
#  echo "*************************************************"
#  exit 1
#fi
#
## Verificar se há algum dispositivo/emulador ativo
#DEVICE_COUNT=$(adb devices | grep -w "device" | wc -l)
#
#if [ "$DEVICE_COUNT" -eq 0 ]; then
#  echo "*************************************************************************"
#  echo "                     UI tests failed                                     "
#  echo " No active devices/emulators found. Instrumented tests will be ignored   "
#  echo "*************************************************************************"
#else
#  # Executar os testes instrumentados
#  ./gradlew connectedAndroidTest
#  RESULT_INSTRUMENTED_TEST=$?
#
#  if [ $RESULT_INSTRUMENTED_TEST -ne 0 ]; then
#    echo "Falha nos testes instrumentados. O push foi abortado."
#    echo "*************************************************************************"
#    echo "                       UI tests failed                                   "
#    echo "           Instrumented tests failed. Push was aborted                   "
#    echo "*************************************************************************"
#    exit 1
#  fi
#fi

# Se tudo estiver correto, o push continua
exit 0
