name: Test Coverage on PR

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:

      - name: Grant permissions to gradle
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-build-cache --no-configuration-cache

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build & Test
        run: ./gradlew clean testDebugUnitTest

      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.kt
            **/*.java

      - name: Parse coverage from report
        run: |
          chmod +x scripts/parse_coverage.sh
          ./scripts/parse_coverage.sh "${{ steps.changed-files.outputs.all_changed_files }}" > coverage_report.md

      - name: Comment coverage on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage_report.md
